### ISSUE TITLE
Code review from team Wiley

### ISSUE THREAD

**Issue by maxwell-sapp** [aiaay/EEP-153-Project-4_Group-Zilberman#1]
Hi Team Zilberman,
Here is our code review from the file “EEP153_Project 4_Zilberman_Draft_Tamil_Nadu.ipynb:”

Positives:
Really appreciated the initial clarification and improvement on the unit issue from project 3 under “Choice of Dataset”
Good explanation on the meaning of alpha and beta, specifically with respect to the effect of higher quantity purchase of luxury goods
Inclusion of Marshallian
Nutrient outcome with respect to a change in budget graph as well as nutrient outcome when there is a change in food prices
Area of Improvement:
Obviously there is no code for West Bengal but the above code replicated looks like it will be very effective in understanding potential policies to put in place
 
Overall, this project is super super interesting and the way in which the code is not only concise but explained thoroughly makes the project easy to dissect and understand. Looking forward to seeing the presentation.

**Comment by aiaay** [comment]
Thank you so much for the constructive feedback! For the final version, we've decided to keep them as two separate notebooks, one for each state for the sake of memory on jupyterhub
